function [out_I_ac_rms, ...
    out_U_sec_rms, ...
    out_f_sec, ...
    out_hv_system_fault, ...
    internal_transformer_loss_power] = behavior(time_s, ...
    in_I_sec_rms, ...
    in_U_ac_rms, ...
    in_f_ac, ...
    in_hv_breaker_state, ...
    in_hv_system_fault)
%#codegen
out_I_ac_rms = 0.0;
out_U_sec_rms = 0.0;
out_f_sec = 0.0;
out_hv_system_fault = int32(0);
internal_transformer_loss_power = 0.0;
ratio = 0.059999999999999998;
eta = 0.96999999999999997;
enabled = (in_hv_breaker_state > 0) && (in_hv_system_fault == 0);
out_U_sec_rms = double(enabled)*ratio*in_U_ac_rms;
out_f_sec = double(enabled)*in_f_ac;
out_I_ac_rms = double(enabled)*abs(in_I_sec_rms)*ratio/eta;
out_hv_system_fault = int32(~enabled && in_hv_system_fault ~= 0);
internal_transformer_loss_power = abs(out_U_sec_rms*in_I_sec_rms)*(1.0-eta);
end