function [out_I_ac_rms, ...
    out_U_ac_rms, ...
    out_f_ac, ...
    out_hv_breaker_command, ...
    out_hv_breaker_state, ...
    out_hv_system_fault, ...
    out_line_current, ...
    out_line_voltage, ...
    out_pantograph_command, ...
    internal_line_power] = behavior(time_s, ...
    in_I_ac_rms, ...
    in_U_ac_rms, ...
    in_f_ac, ...
    in_hv_safety_loop_state, ...
    in_hv_system_fault, ...
    in_pantograph_state)
%#codegen
out_I_ac_rms = 0.0;
out_U_ac_rms = 0.0;
out_f_ac = 0.0;
out_hv_breaker_command = int32(0);
out_hv_breaker_state = int32(0);
out_hv_system_fault = int32(0);
out_line_current = 0.0;
out_line_voltage = 0.0;
out_pantograph_command = int32(0);
internal_line_power = 0.0;
healthy = (in_hv_safety_loop_state > 0) && (in_hv_system_fault == 0);
cmd = int32(healthy && (in_pantograph_state > 0));
out_hv_breaker_command = cmd;
out_hv_breaker_state = cmd;
out_hv_system_fault = int32(~healthy);
out_pantograph_command = int32(1);
out_U_ac_rms = double(cmd)*in_U_ac_rms;
out_f_ac = double(cmd)*in_f_ac;
out_I_ac_rms = double(cmd)*in_I_ac_rms;
out_line_voltage = out_U_ac_rms;
out_line_current = out_I_ac_rms;
internal_line_power = out_line_voltage*out_line_current;
end