function [out_I_sec_rms, ...
    out_U_motor_ll_rms, ...
    out_brake_resistor_dissipated_power, ...
    out_dc_link_current, ...
    out_dc_link_voltage, ...
    out_f_motor_e, ...
    out_grid_acceptable_regenerative_power, ...
    out_grid_returned_power, ...
    out_regenerative_power_actual, ...
    out_traction_converter_fault, ...
    internal_Ptraction, ...
    internal_Pregen] = behavior(time_s, ...
    in_I_motor_rms, ...
    in_U_sec_rms, ...
    in_f_sec, ...
    in_line_current, ...
    in_line_voltage, ...
    in_motor_phase_voltage, ...
    in_motor_speed, ...
    in_motor_torque_actual, ...
    in_motor_torque_request)
%#codegen
out_I_sec_rms = 0.0;
out_U_motor_ll_rms = 0.0;
out_brake_resistor_dissipated_power = 0.0;
out_dc_link_current = 0.0;
out_dc_link_voltage = 0.0;
out_f_motor_e = 0.0;
out_grid_acceptable_regenerative_power = 0.0;
out_grid_returned_power = 0.0;
out_regenerative_power_actual = 0.0;
out_traction_converter_fault = int32(0);
internal_Ptraction = 0.0;
internal_Pregen = 0.0;
persistent Udc;
if isempty(Udc), Udc = 1800; end
dt = 0.10000000000000001;
pmax = 1200000;
targetU = min(2200.0,max(900.0,1.2*max(in_U_sec_rms,1800/1.2)));
Udc = Udc + dt*(targetU-Udc)/0.3;
Treq = min(6000,max(-6000,in_motor_torque_request));
slip = Treq/30;
out_f_motor_e = 3*(in_motor_speed+slip)/(2.0*pi);
out_U_motor_ll_rms = min(0.9*Udc,max(100.0,abs(out_f_motor_e)*8.0));
Pmech = in_motor_torque_actual*in_motor_speed;
Ptr = min(pmax,max(Pmech/0.95999999999999996,0.0));
Preg = min(pmax,max(-Pmech*0.94999999999999996,0.0));
out_dc_link_voltage = Udc;
out_dc_link_current = (Ptr-Preg)/max(Udc,100.0);
out_I_sec_rms = Ptr/max(in_U_sec_rms,100.0);
out_grid_acceptable_regenerative_power = 0;
out_grid_returned_power = min(Preg,out_grid_acceptable_regenerative_power);
out_regenerative_power_actual = Preg;
out_brake_resistor_dissipated_power = max(Preg-out_grid_returned_power-600000.0,0.0);
out_traction_converter_fault = int32(~isfinite(Udc));
internal_Ptraction = Ptr;
internal_Pregen = Preg;
end