"""Validate candidate topology closure, voltage observability, and KG freeze."""
from collections import Counter
from common import *
def main():
 g=graph();c=read(WORK/'candidate_connections.json');n=read(WORK/'candidate_nets.json');cov=read(WORK/'port_coverage.json');role=read(WORK/'product_role_map.json');active={x['port_id']:x for x in active_ports(g)};cands=c['candidates'];nets={x['net_id']:x for x in n['nets']}
 hard=sum(1 for x in cands if not all(x['hard_checks'].values()));bad_end=sum(1 for x in cands if x['source_port_id'] not in active or (x['target_port_id'] and x['target_port_id'] not in active));dupcov=len(cov['coverage'])-len({x['port_id'] for x in cov['coverage']});missing=set(active)-{x['port_id'] for x in cov['coverage']};all_net_ports=[m['port_id'] for x in nets.values() for m in x['members']];net_bad=sum(1 for x in nets.values() for m in x['members'] if m['port_id'] not in active or active[m['port_id']]['item_code']!=x['item_code']);dc=nets['NET-DC-LINK-01'];dc_codes={x['product_code'] for x in dc['members']};modes=Counter(x['connection_mode'] for x in cands);dc_pair_candidates=sum(1 for x in cands if x['item_code']=='ITM-PHY-003' and x['target_port_id']);cross_storage=sum(1 for x in cands if x['target_port_id'] and {active[x['source_port_id']]['item_code'],active[x['target_port_id']]['item_code']}=={'ITM-PHY-003','ITM-PHY-016'});mechanical_shortcuts=sum(1 for x in cands if x['connection_mode']=='SERIES' and x['source_product']=='5311' and x['target_product'] in {'3111','3112','3121'});sensor_in_series=sum(1 for x in cands if x['connection_mode']=='SERIES' and ('SENSOR_TAP' in {x['source_role'],x['target_role']}) )
 def has(a,b,item=None):return any({x['source_product'],x['target_product']}=={a,b} and (not item or x['item_code']==item) for x in cands if x['target_product'])
 closure=[
  {'name':'AC主供电路径','status':'PASS' if all(has(a,b,'ITM-PHY-001') for a,b in [('4111','4211'),('4211','4212'),('4212','4236'),('4236','4511')]) else 'FAIL','missing':'none'},
  {'name':'主变二次交流路径','status':'WARNING','missing':'5121/5122输入链的具体部署/支路选择尚无证据；已阻止高压交流跨主变直连5131。'},
  {'name':'DC Link网络','status':'PASS' if {'5131','5132','5142','X111'}<=dc_codes and not dc['pairwise_clique_generated'] else 'FAIL','missing':'5145无ITM-PHY-003物理口，按实际Port结构作为检测保护信号设备，不伪造Net成员。'},
  {'name':'电机三相交流路径','status':'PASS' if has('5132','5311','ITM-PHY-004') else 'FAIL','missing':'none'},
  {'name':'机械牵引路径','status':'WARNING','missing':'联轴节variant未选择；Motor→候选Coupling→Gearbox高速侧→低速侧→Axle→Wheel候选链均已生成。'},
  {'name':'再生回馈路径','status':'WARNING','missing':'依赖未决Coupling variant；物理候选保持双向，未生成跨级捷径。'},
  {'name':'超级电容储能路径','status':'PASS' if all(x in nets for x in ['NET-STORAGE-DC-BUS-01','NET-STORAGE-DC-AFTER-CONTACTOR-01','NET-STORAGE-DC-SC-01']) and has('X133','X121','ITM-PHY-016') else 'FAIL','missing':'none'},
  {'name':'制动电阻耗散路径','status':'PASS' if '5142' in dc_codes and any(x['source_product']=='5142' and x['connection_mode']=='BOUNDARY' for x in cands) else 'FAIL','missing':'none'},
  {'name':'服务制动控制路径','status':'WARNING','missing':'部分Command存在多源或I/O部署歧义，保留UNRESOLVED而未直接驱动气动设备。'},
  {'name':'ATP/紧急制动路径','status':'WARNING','missing':'E100/8127/安全逻辑的I/O部署与命令仲裁存在UNRESOLVED_ROUTE。'},
  {'name':'气动制动执行路径','status':'WARNING','missing':'候选气动Net已形成，但单端口卡钳的内部力传递粒度不足，不伪造额外Port。'},
  {'name':'主回路回流路径','status':'WARNING','missing':'NET-MAIN-RETURN-01已建立，至轮轨/变电所回流边界的明确端口证据不足。'}]
 voltage={
  'U_grid':{'location':'BOUNDARY-CATENARY-25KV / 4111接触面','ok':any(x['target_boundary']=='BOUNDARY-CATENARY-25KV' for x in cands)},
  'U_transformer_primary':{'location':'4511 ITM-PHY-001 boundary','ok':has('4236','4511','ITM-PHY-001')},
  'U_transformer_secondary':{'location':'4511 ITM-PHY-014 boundary','ok':has('4511','4513','ITM-PHY-014')},
  'U_dc':{'location':'NET-DC-LINK-01','ok':'NET-DC-LINK-01' in nets},
  'U_motor':{'location':'5132↔5311 ITM-PHY-004 boundary','ok':has('5132','5311','ITM-PHY-004')},
  'U_sc':{'location':'NET-STORAGE-DC-SC-01 / X121','ok':'NET-STORAGE-DC-SC-01' in nets and any(x['product_code']=='X121' for x in nets['NET-STORAGE-DC-SC-01']['members'])}}
 voltage_status='PASS' if all(x['ok'] for x in voltage.values()) else 'VOLTAGE_CHAIN_INCOMPLETE';checks={'kg_v1_frozen':freeze_snapshot()['Active_EXPOSES']==511 and freeze_snapshot()['kg_sha256']==role['meta']['kg_sha256'],'coverage_exactly_once':len(cov['coverage'])==511 and not dupcov and not missing,'candidate_endpoints_active':bad_end==0,'hard_rule_violations_zero':hard==0,'net_member_violations_zero':net_bad==0,'unique_net_membership':len(all_net_ports)==len(set(all_net_ports)),'dc_link_not_clique':not dc['pairwise_clique_generated'] and dc_pair_candidates==0,'dc_storage_domains_separated':cross_storage==0,'no_motor_mechanical_shortcuts':mechanical_shortcuts==0,'sensor_taps_not_series':sensor_in_series==0,'no_final_CONNECTS_TO':not c['forbidden_output_created']}
 result={'summary':freeze_snapshot()|{'interface_compatible_raw_candidates':c['meta']['interface_compatible_raw_candidates'],'hard_rule_candidates':len(cands),'candidate_modes':dict(modes),'net_count':len(nets),'net_member_count':sum(len(x['members']) for x in nets.values()),'variant_conflicts':sum(x['status']=='UNRESOLVED_VARIANT' for x in variants()['variant_groups']),'unresolved_routes':len(c['unresolved_routes']),'coverage_counts':cov['meta']['coverage_counts'],'hard_rule_violations':hard},'checks':checks,'global_closure_qa':closure,'voltage_continuity':{'status':voltage_status,'observations':voltage},'overall':'PASS' if all(checks.values()) and voltage_status=='PASS' and not any(x['status']=='FAIL' for x in closure) else 'FAIL'};write(WORK/'topology_qa.json',result)
 # Reports are generated only from reread artifacts/results.
 route_lines=''.join(f"- `{x['target_port_id']}` / {x['item_code']}: {x['reason']}\n" for x in c['unresolved_routes']);issue_lines=''.join(f"- {x['type']} `{x['target_port_id']}`: {', '.join(x['source_products'])}\n" for x in c['issues'])
 (REPORTS/'candidate_connection_report.md').write_text('# Candidate Connection Report\n\n'+f"- Interface-compatible raw candidates: {result['summary']['interface_compatible_raw_candidates']}\n- Hard-rule candidates: {len(cands)}\n"+''.join(f"- {k}: {v}\n" for k,v in sorted(modes.items()))+f"- Candidate nets: {len(nets)}\n- Net members: {result['summary']['net_member_count']}\n- Variant conflicts: {result['summary']['variant_conflicts']}\n- UNRESOLVED_ROUTE: {result['summary']['unresolved_routes']}\n- Hard-rule violations: {hard}\n- Final CONNECTS_TO created: no\n\n## UNRESOLVED_ROUTE\n\n"+route_lines+'\n## Command cardinality unresolved\n\n'+issue_lines,encoding='utf-8')
 clines=['# Port Coverage Report','',f"- total_active_ports: {len(cov['coverage'])}"]+[f"- {k.lower()}: {v}" for k,v in sorted(cov['meta']['coverage_counts'].items())]+['',f"## UNRESOLVED ({len(cov['unresolved'])})",'']+[f"- `{x['port_id']}` — {x['reason']}" for x in cov['unresolved']];(REPORTS/'port_coverage_report.md').write_text('\n'.join(clines)+'\n',encoding='utf-8')
 qlines=['# Topology QA Report','',f"- Overall: {result['overall']}",f"- Voltage Continuity: {voltage_status}",f"- Hard-rule violations: {hard}",'','## 12 Global Closure Checks','']+[f"- {x['name']}: **{x['status']}** — {x['missing']}" for x in closure]+['','## Voltage observation locations','']+[f"- {k}: {'PASS' if v['ok'] else 'FAIL'} — {v['location']}" for k,v in voltage.items()]+['','## Structural checks','']+[f"- {k}: {'PASS' if v else 'FAIL'}" for k,v in checks.items()];(REPORTS/'topology_qa_report.md').write_text('\n'.join(qlines)+'\n',encoding='utf-8');print(json.dumps(result,ensure_ascii=False))
 if result['overall']!='PASS':raise SystemExit(1)
if __name__=='__main__':main()
