import {ArrowRightOutlined,DatabaseOutlined,SearchOutlined} from '@ant-design/icons'
import {Button,Card,Descriptions,Drawer,Empty,Input,List,Select,Space,Spin,Statistic,Table,Tabs,Tag,Typography} from 'antd'
import {useEffect,useMemo,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import TraceGraph from '../components/semantic/TraceGraph'
import {semanticApi} from '../services/semanticApi'

const examples=['我想看再生制动','我想看制动系统','我想看能量回收','我只想看X100','我想看牵引系统','我想看制动时为什么需要机械制动']
const typeLabel:Record<string,string>={STANDARD_DIRECT:'标准直接需求',PROJECT_REQUIREMENT:'项目设计需求'}
const statusLabel:Record<string,string>={VERIFIED:'已验证',PARTIALLY_VERIFIED:'部分验证',NOT_VERIFIED:'尚未建立完整验证证据'}
function SmallTags({values}:{values:any}){const list=Array.isArray(values)?values:String(values||'').split(';');return <Space size={[4,4]} wrap>{list.filter(Boolean).map((x:string)=><Tag key={x}>{x}</Tag>)}</Space>}

export default function SemanticRequirementPage(){
  const nav=useNavigate(),[summary,setSummary]=useState<any>(),[requirements,setRequirements]=useState<any[]>([]),[functions,setFunctions]=useState<any[]>([]),[products,setProducts]=useState<any[]>([])
  const [query,setQuery]=useState('我想看再生制动能量回收'),[result,setResult]=useState<any>(),[loading,setLoading]=useState(false),[drawer,setDrawer]=useState<any>(),[filters,setFilters]=useState<any>({})
  const run=async(value=query)=>{if(!value.trim())return;setQuery(value);setLoading(true);try{setResult(await semanticApi.query(value))}finally{setLoading(false)}}
  useEffect(()=>{Promise.all([semanticApi.catalog(),semanticApi.requirements(),semanticApi.functions(),semanticApi.products()]).then(([s,r,f,p])=>{setSummary(s);setRequirements(r);setFunctions(f);setProducts(p)});void run('我想看再生制动能量回收')},[])
  const openEntity=async(type:string,id:string)=>{const data=type==='requirement'?await semanticApi.requirement(id):type==='function'?await semanticApi.function(id):await semanticApi.product(id);setDrawer({type,id,data})}
  const filtered=useMemo(()=>requirements.filter(r=>(!filters.domain||r.domain===filters.domain)&&(!filters.type||r.requirement_type===filters.type)&&(!filters.status||r.verification_status===filters.status)),[requirements,filters])
  if(!summary)return <Spin/>
  const stats=[['正式需求',summary.requirement_count],['系统功能',summary.function_count],['系统产品',summary.product_count],['追溯关系',summary.trace_relation_count],['已验证',summary.verified_requirement_count]]
  const resultView=<><div className="semantic-pipeline"><div><small>用户问题</small><b>{result?.query||query}</b></div><ArrowRightOutlined/><div><small>Requirement</small><b>{result?.stats?.requirement_count||0} 项需求</b></div><ArrowRightOutlined/><div><small>Function</small><b>{result?.stats?.function_count||0} 项功能</b></div><ArrowRightOutlined/><div><small>Product</small><b>{result?.stats?.product_count||0} 个产品</b></div></div>
    {result&&<div className="semantic-query-meta"><Tag color={result.interpretation.scope==='broad'?'blue':'cyan'}>检索范围：{result.interpretation.scope==='broad'?'广义':'聚焦'}</Tag><Tag>语义引擎 · {result.provider}</Tag>{result.cache_hit&&<Tag>缓存命中</Tag>}<span>{result.interpretation.summary}</span></div>}
    <Card className="semantic-graph-card" title="Question → Requirement → Function → Product" extra={<span>点击节点查看来源与映射证据</span>}><TraceGraph result={result} onEntity={openEntity}/></Card>
    <div className="semantic-columns"><Card title={`需求 REQUIREMENT · ${result?.requirements?.length||0}`}>{result?.requirements?.length?<List dataSource={result.requirements} renderItem={(x:any)=><List.Item onClick={()=>void openEntity('requirement',x.requirement_id)} className="semantic-list-item"><List.Item.Meta title={<Space><b>{x.requirement_id}</b><Tag>{typeLabel[x.source_type]||x.source_type}</Tag></Space>} description={<><div>{x.name}</div><small>{x.match_reason} · score仅用于排序 {Number(x.semantic_score).toFixed(2)}</small></>}/></List.Item>}/>:<Empty description="未命中工程需求"/>}</Card>
      <Card title={`功能 FUNCTION · ${result?.functions?.length||0}`}><List dataSource={result?.functions||[]} renderItem={(x:any)=><List.Item onClick={()=>void openEntity('function',x.function_id)} className="semantic-list-item"><List.Item.Meta title={x.function_id} description={<><div>{x.name}</div><small>由 {x.matched_by_requirements?.length||0} 条 Requirement 命中</small></>}/></List.Item>}/></Card>
      <Card title={`产品 PRODUCT · ${result?.products?.length||0}`}><List dataSource={result?.products||[]} renderItem={(x:any)=><List.Item onClick={()=>void openEntity('product',x.product_id)} className="semantic-list-item"><List.Item.Meta title={`${x.product_id} · ${x.name}`} description={`承载 ${x.matched_by_functions?.length||0} 项 Function`}/></List.Item>}/></Card></div>
    {result?.requirements?.length>0&&<Card className="semantic-explain" title="为什么命中"><Descriptions column={3} items={[{key:'q',label:'用户问题',children:result.query},{key:'k',label:'识别关键词',children:<SmallTags values={result.interpretation.keywords}/>},{key:'basis',label:'匹配依据',children:'需求名称、关键词、同义词、用户表达、功能语义及已关联产品'}]}/></Card>}</>
  return <div className="semantic-page"><section className="semantic-hero"><div><Typography.Title level={2}>需求语义解析与模型追溯</Typography.Title><p>从自然语言需求定位 Requirement，并沿本地工程真值追溯到系统功能与产品架构</p></div><Tag className="semantic-engine">语义引擎 · {summary.provider}</Tag><div className="semantic-search"><Input size="large" value={query} onChange={e=>setQuery(e.target.value)} onPressEnter={()=>void run()} prefix={<SearchOutlined/>} placeholder="输入你关心的系统需求，例如：我想看再生制动时能量是如何回收的"/><Button size="large" type="primary" loading={loading} onClick={()=>void run()}>解析需求</Button></div><Space wrap className="semantic-chips">{examples.map(x=><Button size="small" key={x} onClick={()=>void run(x)}>{x}</Button>)}</Space></section>
    <div className="semantic-stats">{stats.map(([name,value])=><Statistic key={String(name)} title={name} value={value}/>)}</div>
    <Tabs defaultActiveKey="result" items={[{key:'result',label:'语义结果',children:resultView},{key:'requirements',label:`全部需求 (${requirements.length})`,children:<><Space className="semantic-filters"><Select allowClear placeholder="Domain" onChange={v=>setFilters((p:any)=>({...p,domain:v}))} options={[...new Set(requirements.map(x=>x.domain))].map(x=>({label:x,value:x}))}/><Select allowClear placeholder="Requirement Type" onChange={v=>setFilters((p:any)=>({...p,type:v}))} options={[...new Set(requirements.map(x=>x.requirement_type))].map(x=>({label:x,value:x}))}/><Select allowClear placeholder="Verification" onChange={v=>setFilters((p:any)=>({...p,status:v}))} options={[...new Set(requirements.map(x=>x.verification_status))].map(x=>({label:x,value:x}))}/></Space><Table rowKey="requirement_id" size="small" pagination={{pageSize:10}} dataSource={filtered} onRow={x=>({onClick:()=>void openEntity('requirement',x.requirement_id)})} columns={[{title:'ID',dataIndex:'requirement_id'},{title:'需求',dataIndex:'name'},{title:'领域',dataIndex:'domain'},{title:'来源',dataIndex:'source_type',render:(v:string)=><Tag>{typeLabel[v]||v}</Tag>},{title:'验证',dataIndex:'verification_status',render:(v:string)=><Tag color={v==='VERIFIED'?'green':v==='PARTIALLY_VERIFIED'?'blue':'default'}>{statusLabel[v]||v}</Tag>}]}/></>},{key:'functions',label:`全部功能 (${functions.length})`,children:<List className="semantic-catalog-list" dataSource={functions} pagination={{pageSize:12}} renderItem={(x:any)=><List.Item onClick={()=>void openEntity('function',x.function_id)}><List.Item.Meta title={`${x.function_id} · ${x.name}`} description={`${x.category||'Function'} · allocation → ${x.product_ids.join(', ')}`}/></List.Item>}/>},{key:'products',label:`全部产品 (${products.length})`,children:<List className="semantic-catalog-list" dataSource={products} pagination={{pageSize:12}} renderItem={(x:any)=><List.Item onClick={()=>void openEntity('product',x.product_id)}><List.Item.Meta title={`${x.product_id} · ${x.name}`} description={`L${x.level} · ${x.function_ids.length} 项已分配功能`}/></List.Item>}/>} ]}/>
    <Drawer width={560} open={!!drawer} onClose={()=>setDrawer(null)} title={drawer&&`${drawer.type.toUpperCase()} · ${drawer.id}`} extra={drawer?.type==='function'?<Button type="primary" onClick={()=>nav(`/task-slice?function=${encodeURIComponent(drawer.id)}`)}>进入任务切片</Button>:drawer?.type==='product'?<Button type="primary" onClick={()=>nav(`/sysml?focus=${encodeURIComponent(drawer.id)}`)}>查看 SysML 模型</Button>:null}>{drawer&&<EntityDetail drawer={drawer} openEntity={openEntity}/>}</Drawer></div>
}

function EntityDetail({drawer,openEntity}:{drawer:any;openEntity:(type:string,id:string)=>void}){const root=drawer.data,entity=root.requirement||root.function||root.product;return <><Descriptions column={1} bordered size="small" items={Object.entries(entity||{}).filter(([,v])=>typeof v!=='object'&&v!==''&&v!==null).map(([k,v])=>({key:k,label:k,children:String(v)}))}/>{entity?.keywords?.length>0&&<Card size="small" title="Keywords" className="semantic-detail-card"><SmallTags values={entity.keywords}/></Card>}{entity?.synonyms?.length>0&&<Card size="small" title="Synonyms" className="semantic-detail-card"><SmallTags values={entity.synonyms}/></Card>}{root.functions?.length>0&&<Card size="small" title="Functions 与映射证据" className="semantic-detail-card">{root.functions.map((x:any)=><div className="semantic-evidence" key={x.function_id}><Button type="link" onClick={()=>void openEntity('function',x.function_id)}>{x.function_id} · {x.name}</Button><p>{x.mapping?.mapping_source} · {x.mapping?.evidence}</p></div>)}</Card>}{root.requirements?.length>0&&<Card size="small" title="Requirements" className="semantic-detail-card">{root.requirements.map((x:any)=><Button type="link" block key={x.requirement_id} onClick={()=>void openEntity('requirement',x.requirement_id)}>{x.requirement_id} · {x.name}</Button>)}</Card>}{root.products?.length>0&&<Card size="small" title="Products 与正式 allocation" className="semantic-detail-card">{root.products.map((x:any)=><div className="semantic-evidence" key={x.product_id}><Button type="link" onClick={()=>void openEntity('product',x.product_id)}>{x.product_id} · {x.name}</Button><p>{x.mapping?.mapping_source} · {x.mapping?.evidence}</p></div>)}</Card>}<div className="semantic-source"><DatabaseOutlined/> 工程来源：{entity?.source_file||entity?.source||'—'}</div></>}
