function [out_I_ac_rms, ...
    out_U_ac_rms, ...
    out_f_ac, ...
    out_hv_breaker_command, ...
    out_hv_breaker_state, ...
    out_hv_system_fault, ...
    out_line_current, ...
    out_line_voltage, ...
    out_pantograph_command, ...
    internal_line_power, ...
    internal_hv_available] = behavior(time_s, ...
    in_I_ac_rms, ...
    in_U_ac_rms, ...
    in_f_ac, ...
    in_hv_safety_loop_state, ...
    in_hv_system_fault, ...
    in_pantograph_state)
%#codegen
out_I_ac_rms = 0.0;
out_U_ac_rms = 0.0;
out_f_ac = 0.0;
out_hv_breaker_command = int32(0);
out_hv_breaker_state = int32(0);
out_hv_system_fault = int32(0);
out_line_current = 0.0;
out_line_voltage = 0.0;
out_pantograph_command = int32(0);
internal_line_power = 0.0;
internal_hv_available = 0.0;
persistent breaker closeTimer;
if isempty(breaker), breaker = int32(0); closeTimer = 0.0; end
dt = 0.01;
supplyValid = (in_pantograph_state > 0) && (in_U_ac_rms >= 15000) && (in_f_ac >= 45) && (in_f_ac <= 55);
safetyClosed = (in_hv_safety_loop_state > 0);
downstreamTrip = (in_hv_system_fault ~= 0);
cmd = int32(safetyClosed && supplyValid && ~downstreamTrip);
out_hv_breaker_command = cmd;
if cmd > 0, closeTimer = min(0.29999999999999999,closeTimer+dt); else, closeTimer = 0.0; breaker = int32(0); end
if closeTimer >= 0.29999999999999999, breaker = int32(1); end
out_hv_breaker_state = breaker;
trueFault = ((in_pantograph_state > 0) && ~supplyValid) || downstreamTrip;
out_hv_system_fault = int32(trueFault);
out_pantograph_command = int32(1);
out_U_ac_rms = double(breaker)*in_U_ac_rms;
out_f_ac = double(breaker)*in_f_ac;
out_I_ac_rms = double(breaker)*in_I_ac_rms;
out_line_voltage = out_U_ac_rms;
out_line_current = out_I_ac_rms;
internal_line_power = out_line_voltage*out_line_current;
internal_hv_available = double(breaker > 0 && ~trueFault);
end